version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: incighder
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c 'fsync=off'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  

  incighder-dev:
    build:
      context: ./incighder
      dockerfile: Dockerfile.dev
    volumes:
      - ./incighder:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      data-api:
        condition: service_healthy

  data-api:
    build:
      context: .
      dockerfile: ./scraper/Dockerfile
    volumes:
      - ./scraper:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGUSER: postgres
      PGPASSWORD: password
      PGDATABASE: incighder
      PGHOST: db
    command: python app.py
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import socket; s = socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.connect((\"localhost\", 5000)); s.close()'"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: